language: go
go:
  - "1.12.x"

cache:
  directories:
    - $HOME/.ccache

env:

matrix:
  include:
    - os: linux
      cache:
        directories:
          - $HOME/.cache/go-build
      sudo: required
      env:
        - DOCKER_IMG_VERSION=0.2
        - ARCH=amd64
      before_install:
        - sudo apt-get install jq
    - os: linux
      cache:
        directories:
          - $HOME/.cache/go-build
      arch: arm64
      sudo: required
      env:
        - ARCH=arm
        - CC=arm-linux-gnueabihf-gcc
        - DOCKER_IMG_VERSION=0.2
        - RUNU_PATH="linux_arm/"
        - DOCKER_RUN_ARGS_ARCH="--platform=linux/arm"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt-get update && sudo apt-get install jq libc6:armhf crossbuild-essential-armhf
        - export CGO_ENABLED=1
        - export GOARCH=arm
        - export PATH=$GOPATH/bin/linux_arm:$PATH
    - os: osx
      osx_image: xcode10.1
      cache:
        directories:
          - $HOME/Library/Caches/go-build
      env:
        - DOCKER_IMG_VERSION=0.2
        - ARCH=amd64
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask info tuntap
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ukontainer/lkl/dockerd-darwin
        - mkdir -p ~/.local/bin
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - ln -sf /usr/local/bin/gsha256sum ~/.local/bin/sha256sum
    - os: osx
      osx_image: xcode10.2
      cache:
        directories:
          - $HOME/Library/Caches/go-build
      env:
        - DOCKER_IMG_VERSION=0.2
        - ARCH=amd64
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask info tuntap
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ukontainer/lkl/dockerd-darwin
        - mkdir -p ~/.local/bin
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - ln -sf /usr/local/bin/gsha256sum ~/.local/bin/sha256sum

before_script:
  - go get -u github.com/gojp/goreportcard/cmd/goreportcard-cli
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint

script:
  - if [ $TRAVIS_ARCH = "amd64" ] && [ $TRAVIS_OS_NAME = "linux" ] ; then goreportcard-cli -t 100.0 -v ; fi
  - bash -ex test/standalone-test.sh
  - bash -ex test/docker-oci-test.sh
  - bash -ex test/containerd-ctr-test.sh

after_failure:
  - cat $HOME/dockerd.log
  - cat $HOME/containerd.log
