name: Go
on: [push]
    
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .
      
    - name: Test (standalone)
      run: bash -ex ${GITHUB_WORKSPACE}/test/standalone-test.sh
    - name: Test (dockerd)
      run: bash -ex ${GITHUB_WORKSPACE}/test/docker-oci-test.sh
    - name: Test (containerd/ctr)
      run: bash -ex ${GITHUB_WORKSPACE}/test/containerd-ctr-test.sh
      
    
